### ISSUE TITLE
CITATION.cff hinzufügen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#646]
Siehe:
- https://citation-file-format.github.io/cff-initializer-javascript/#/
-  https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#preferred-citation
- https://github.com/hitontology/ontology/blob/master/CITATION.cff

```
# This CITATION.cff file was generated with cffinit.
# Visit https://bit.ly/cffinit to generate yours today!

cff-version: 1.2.0
title: CDS Tool Chain
message: Please cite us.
type: software
authors:
  - orcid: 'https://orcid.org/0000-0002-7221-7415'
    given-names: Sebastian
    family-names: Stäubert
    email: sebastian.staeubert@imise.uni-leipzig.de
    name-particle: Stäubert
    affiliation: Universität Leipzig
repository-code: 'https://github.com/medizininformatik-initiative/INTERPOLAR'
url: 'https://medizininformatik-initiative.github.io/INTERPOLAR/'
abstract: >-
  The CDS Tool Chain is a modular reference implementation
  that can be used, for example, by MII data integration
  centers (DIC). FHIR resources are downloaded from the KDS
  (core data set) FHIR server / endpoint, converted into a
  table structure (CDS2DB) and written to a Posgres database
  (CDS_HUB). In a next step, the data is checked, harmonized
  and can be further processed with the help of algorithms
  (DataProcessor). The data is then made visible on a user
  interface via a frontend (e.g. Redcap) (DB2Frontend,
  Frontend).
keywords:
  - Medical Informatics
  - Core Data Set
  - Medical Informatics Initiative
  - HL7 FHIR
  - Medical Data Science
  - Distributed Processing
license: Apache-2.0
```
